version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - sightreadpro-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - sightreadpro-network

  # Optional: PostgreSQL database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sightreadpro
      POSTGRES_USER: sightreadpro_user
      POSTGRES_PASSWORD: sightreadpro_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - sightreadpro-network

volumes:
  redis_data:
  postgres_data:

networks:
  sightreadpro-network:
    driver: bridge


